name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: snok/install-poetry@v1
        with:
          poetry-version: '1.8.2'

      - run: poetry install --no-ansi --with dev
      - run: poetry run pytest -q

  docker-training:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push training image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.training
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/training_pipeline:latest,${{ secrets.DOCKERHUB_USERNAME }}/training_pipeline:${{ github.sha }}

  docker-api:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push api image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/inference_api:latest,${{ secrets.DOCKERHUB_USERNAME }}/inference_api:${{ github.sha }}
docker-ui:
  runs-on: ubuntu-latest
  needs: test
  permissions:
    contents: read
    packages: write
  steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & push ui image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile.ui
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/streamlit_ui:latest,${{ secrets.DOCKERHUB_USERNAME }}/streamlit_ui:${{ github.sha }}
