# Usa una imagen base de Python
FROM python:3.7.16

# Define el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos del proyecto al contenedor
COPY /app/. /app/
COPY /models/. /app/models/


RUN pip install numpy pandas FastApi "scikit-learn==1.0.2" uvicorn

# Expone el puerto donde correrá el API
EXPOSE 8989

# Comando para ejecutar el API cuando el contenedor se inicie
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8989"]
