apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlops.fullname" . }}-api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: {{ include "mlops.fullname" . }}-api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8000
